// boomi.config.js
export const boomiConfig = {
    theme: {
      allowThemes: true,
      defaultTheme: 'plex'
    },
    ai: {
      enabled: true,
      model: 'gpt-4o-2024-08-06',
      apiKey: import.meta.env.VITE_OPENAI_API_KEY,
    },
  
    // Per-theme overrides
    cssVarsByTheme: {
      /* ========= PLEX (minimal) ========= */
      plex: {
        /* Font */
        '--boomi-font': 'Inter, ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, "Noto Sans", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
        '--default-font-family': 'var(--boomi-font)',
  
        /* Brand tokens (internal helpers) */
        '--plex-blue': '#0096D5',
        '--plex-navy': '#2E2F3B',
        '--plex-gray': '#57626E',
        '--plex-light-gray': '#E3E8E8',
        '--plex-orange': '#E2870F',
        '--plex-white': '#FFFFFF',
  
        /* Root / Page */
        '--boomi-root-bg-color': '#FFFFFF',
        '--boomi-root-fg-color': '#111827',
        '--boomi-page-bg-color': '#FFFFFF',
        '--boomi-page-fg-color': '#111827',
  
        /* Header */
        '--boomi-header-bg-color': '#FFFFFF',
        '--boomi-header-fg-color': '#111827',
        '--boomi-header-fg-hover': '#0096D5',
        '--boomi-header-border-color': '#E5E7EB',
        '--boomi-header-shadow': '0 1px 2px rgba(17,24,39,0.06)',
  
        /* Buttons */
        '--boomi-btn-primary-bg': 'var(--plex-blue)',
        '--boomi-btn-primary-fg': '#FFFFFF',
        '--boomi-btn-primary-border': 'transparent',
        '--boomi-btn-primary-shadow': '0 1px 2px rgba(17,24,39,0.08)',
        '--boomi-btn-primary-bg-hover': '#008BC6',
        '--boomi-btn-primary-bg-active': '#007FB5',
  
        '--boomi-btn-secondary-bg': '#F3F4F6',
        '--boomi-btn-secondary-fg': '#111827',
        '--boomi-btn-secondary-border': '#E5E7EB',
        '--boomi-btn-secondary-shadow': '0 1px 2px rgba(17,24,39,0.06)',
        '--boomi-btn-secondary-bg-hover': '#E5E7EB',
        '--boomi-btn-secondary-bg-active': '#D1D5DB',
  
        /* Inputs */
        '--boomi-input-bg': '#FFFFFF',
        '--boomi-input-fg': '#111827',
        '--boomi-input-placeholder': '#6B7280',
        '--boomi-input-border': '#E5E7EB',
        '--boomi-input-shadow': '0 1px 2px rgba(17,24,39,0.04)',
        '--boomi-input-border-focus': 'var(--plex-blue)',
        '--boomi-input-shadow-focus': '0 0 0 4px rgba(0,150,213,0.15)',
        '--boomi-input-outline-focus': 'transparent',
  
        /* Tables */
        '--boomi-table-header-bg': '#F9FAFB',
        '--boomi-table-header-fg': '#374151',
        '--boomi-table-header-border': '#E5E7EB',
        '--boomi-table-row-odd-bg': '#FFFFFF',
        '--boomi-table-row-even-bg': '#FAFAFA',
        '--boomi-table-row-hover-shadow': 'inset 0 0 0 9999px rgba(0,150,213,0.05)',
  
        /* Cards */
        '--boomi-card-border': '#E5E7EB',
        '--boomi-card-bg': '#FFFFFF',
        '--boomi-card-shadow': '0 1px 3px rgba(17,24,39,0.08)',
        '--boomi-card-hover-shadow': '0 2px 6px rgba(17,24,39,0.10)',
        '--boomi-card-hover-scale': 'none',
  
        /* Menus */
        '--boomi-menu-bg': '#FFFFFF',
        '--boomi-menu-fg': '#111827',
        '--boomi-menu-border': '#E5E7EB',
        '--boomi-menu-shadow': '0 8px 24px rgba(17,24,39,0.08)',
        '--boomi-menu-item-bg': 'transparent',
        '--boomi-menu-item-bg-hover': 'rgba(0,150,213,0.08)',
        '--boomi-menu-item-fg': '#111827',
        '--boomi-menu-item-fg-hover': '#111827',
        '--boomi-menu-divider': '#E5E7EB',
        '--boomi-menu-danger-fg': '#B91C1C',
        '--boomi-menu-danger-fg-hover': '#991B1B',
        '--boomi-menu-danger-bg-hover': '#FEE2E2',
  
        /* Modal */
        '--boomi-modal-overlay-bg': 'rgba(17,24,39,0.45)',
        '--boomi-modal-bg': '#FFFFFF',
        '--boomi-modal-fg': '#111827',
        '--boomi-modal-border': '1px solid #E5E7EB',
        '--boomi-modal-shadow': '0 16px 48px rgba(17,24,39,0.16)',
        '--boomi-modal-close-fg': '#6B7280',
        '--boomi-modal-close-hover-fg': '#111827',
  
        /* Input (stateful) */
        '--boomi-input-bg-disabled': '#F9FAFB',
        '--boomi-input-fg-disabled': '#9CA3AF',
        '--boomi-input-border-disabled': '#E5E7EB',
        '--boomi-input-border-invalid': '#F87171',
        '--boomi-input-outline-invalid': 'rgba(248,113,113,0.25)',
  
        /* Form text */
        '--boomi-form-label-fg': '#374151',
        '--boomi-form-helper-fg': '#6B7280',
        '--boomi-form-error-fg': '#B91C1C',
        '--boomi-form-required-fg': '#DC2626',
  
        /* Select */
        '--boomi-select-bg': '#FFFFFF',
        '--boomi-select-fg': '#111827',
        '--boomi-select-border': '#E5E7EB',
        '--boomi-select-shadow': '0 1px 2px rgba(17,24,39,0.04)',
        '--boomi-select-border-focus': 'var(--plex-blue)',
        '--boomi-select-shadow-focus': '0 0 0 4px rgba(0,150,213,0.15)',
        '--boomi-select-icon': '#6B7280',
        '--boomi-options-bg': '#FFFFFF',
        '--boomi-options-fg': '#111827',
        '--boomi-options-border': '#E5E7EB',
        '--boomi-options-shadow': '0 8px 24px rgba(17,24,39,0.10)',
        '--boomi-options-search-bg': '#F9FAFB',
        '--boomi-option-bg-active': 'rgba(0,150,213,0.10)',
        '--boomi-option-fg-selected': '#111827',
  
        /* Ajax Loader */
        '--boomi-loader-dot-bg': 'var(--plex-blue)',
        '--boomi-loader-dot-size': '0.75rem',
        '--boomi-loader-dot1-opacity': '1',
        '--boomi-loader-dot2-opacity': '1',
        '--boomi-loader-dot3-opacity': '1',
        '--boomi-loader-msg-fg': '#4B5563',
  
        /* Spinner */
        '--boomi-spinner-overlay-bg': 'rgba(255,255,255,0.65)',
        '--boomi-spinner-ring-color': 'var(--plex-blue)',
        '--boomi-spinner-ping-color': '#93D3DF',
        '--boomi-spinner-message-fg': '#374151',
        '--boomi-spinner-size': '3.25rem',
        '--boomi-spinner-border-width': '4px',
  
        /* Wizard */
        '--boomi-wizard-step-dot-bg': '#F3F4F6',
        '--boomi-wizard-step-dot-fg': '#374151',
        '--boomi-wizard-step-dot-border': '#E5E7EB',
        '--boomi-wizard-step-dot-shadow': '0 1px 2px rgba(17,24,39,0.04)',
        '--boomi-wizard-step-dot-bg-active': 'var(--plex-blue)',
        '--boomi-wizard-step-dot-fg-active': '#FFFFFF',
        '--boomi-wizard-step-dot-border-active': 'transparent',
        '--boomi-wizard-step-dot-shadow-active': '0 1px 2px rgba(0,150,213,0.25)',
        '--boomi-wizard-step-dot-bg-completed': '#10B981',
        '--boomi-wizard-step-dot-fg-completed': '#064E3B',
        '--boomi-wizard-step-dot-border-completed': 'transparent',
        '--boomi-wizard-step-dot-shadow-completed': '0 1px 2px rgba(16,185,129,0.25)',
        '--boomi-wizard-connector-bg': '#E5E7EB',
        '--boomi-wizard-label-fg': '#4B5563',
        '--boomi-wizard-card-bg': '#FFFFFF',
        '--boomi-wizard-card-fg': '#111827',
        '--boomi-wizard-card-border': '#E5E7EB',
        '--boomi-wizard-card-shadow': '0 1px 3px rgba(17,24,39,0.08)',
        '--boomi-wizard-link-fg': 'var(--plex-blue)',
        '--boomi-wizard-link-fg-hover': '#007FB5',
        '--boomi-wizard-link-strong-fg': '#111827',
  
        /* Notifications */
        '--boomi-notice-warning-bg': '#FFFBEB',
        '--boomi-notice-warning-fg': '#92400E',
        '--boomi-notice-warning-border': '#FDE68A',
        '--boomi-notice-success-bg': '#ECFDF5',
        '--boomi-notice-success-fg': '#065F46',
        '--boomi-notice-success-border': '#A7F3D0',
        '--boomi-notice-error-bg': '#FEF2F2',
        '--boomi-notice-error-fg': '#991B1B',
        '--boomi-notice-error-border': '#FECACA',
        '--boomi-notice-shadow': '0 1px 2px rgba(17,24,39,0.06)',
        '--boomi-notice-radius': '.5rem',
  
        /* Update panel */
        '--boomi-update-bg': '#FFFFFF',
        '--boomi-update-fg': '#111827',
        '--boomi-update-border': '#E5E7EB',
        '--boomi-update-shadow': '0 2px 6px rgba(17,24,39,0.10)',
        '--boomi-update-title-fg': '#111827',
        '--boomi-update-desc-fg': '#4B5563',
        '--boomi-update-radius': '.5rem',
        '--boomi-update-content': '#111827',
  
        /* Tabs */
        '--boomi-tablist-border': '#E5E7EB',
        '--boomi-tab-bg': '#FFFFFF',
        '--boomi-tab-fg': '#374151',
        '--boomi-tab-border': '#E5E7EB',
        '--boomi-tab-bg-hover': '#F3F4F6',
        '--boomi-tab-bg-active': 'rgba(0,150,213,0.08)',
        '--boomi-tab-fg-active': '#111827',
        '--boomi-tab-border-active': 'var(--plex-blue)',
  
        /* Maps */
        '--boomi-accent': 'var(--plex-blue)',
        '--boomi-muted': '#6B7280',
        '--boomi-map-line': '#CBD5E1',
        '--boomi-map-line-width': '2px',
        '--boomi-map-line-filter': 'none',
        '--boomi-map-heading-fg': '#111827',
        '--boomi-map-card-bg': '#FFFFFF',
        '--boomi-map-card-border': '#E5E7EB',
        '--boomi-map-card-shadow': '0 1px 3px rgba(17,24,39,0.08)',
        '--boomi-map-card-shadow-hover': '0 2px 6px rgba(17,24,39,0.12)',
        '--boomi-map-card-transform-hover': 'none',
        '--boomi-map-source-bg-mapped': '#F1F5F9',
        '--boomi-map-source-border-mapped': '#E5E7EB',
        '--boomi-map-source-outline': '#E5E7EB',
        '--boomi-map-target-bg-mapped': '#F0FDF4',
        '--boomi-map-target-border-mapped': '#DCFCE7',
        '--boomi-map-target-outline': '#DCFCE7',
        '--boomi-map-func-bg': '#F9FAFB',
        '--boomi-map-func-fg': '#111827',
        '--boomi-map-func-title-fg': 'var(--plex-navy)',
        '--boomi-map-pin-source-bg': '#0096D5',
        '--boomi-map-pin-target-bg': '#10B981',
        '--boomi-map-pin-input-bg': '#F59E0B',
        '--boomi-map-pin-output-bg': '#6366F1',
        '--boomi-map-pin-badge-bg': '#EF4444',
        '--boomi-map-pin-badge-fg': '#FFFFFF',
        '--boomi-map-pin-danger-bg': '#EF4444',
        '--boomi-map-pulse-color': 'rgba(0,150,213,0.20)',
        '--boomi-map-pin-pulse': 'boomi-map-pulse 1.1s ease-in-out infinite',
        '--boomi-map-add-bg': '#F3F4F6',
        '--boomi-map-add-fg': '#111827',
        '--boomi-map-add-border': '#E5E7EB',
        '--boomi-map-add-shadow': '0 1px 2px rgba(17,24,39,0.06)',
        '--boomi-map-add-bg-hover': '#E5E7EB',
  
        /* Schedule */
        '--boomi-sched-card-bg': '#FFFFFF',
        '--boomi-sched-card-fg': '#111827',
        '--boomi-sched-card-border': '#E5E7EB',
        '--boomi-sched-card-shadow': '0 1px 3px rgba(17,24,39,0.08)',
        '--boomi-sched-card-shadow-hover': '0 2px 6px rgba(17,24,39,0.12)',
        '--boomi-sched-card-radius': '.5rem',
        '--boomi-sched-header-bg': '#F9FAFB',
        '--boomi-sched-header-fg': '#111827',
        '--boomi-sched-header-border': '#E5E7EB',
        '--boomi-sched-header-shadow': '0 1px 2px rgba(17,24,39,0.06)',
        '--boomi-sched-toggle-fg': '#6B7280',
        '--boomi-sched-toggle-fg-hover': '#111827',
        '--boomi-sched-row-bg': '#FFFFFF',
        '--boomi-sched-row-border': '#E5E7EB',
        '--boomi-sched-row-shadow': '0 1px 2px rgba(17,24,39,0.04)',
        '--boomi-sched-row-hover-shadow': 'inset 0 0 0 9999px rgba(0,150,213,0.05)',
        '--boomi-sched-label-fg': '#374151',
        '--boomi-sched-helper-fg': '#6B7280',
        '--boomi-sched-error-fg': '#B91C1C',
        '--boomi-sched-select-bg': '#FFFFFF',
        '--boomi-sched-select-fg': '#111827',
        '--boomi-sched-select-border': '#E5E7EB',
        '--boomi-sched-select-shadow': '0 1px 2px rgba(17,24,39,0.04)',
        '--boomi-sched-select-border-focus': 'var(--plex-blue)',
        '--boomi-sched-select-shadow-focus': '0 0 0 4px rgba(0,150,213,0.15)',
        '--boomi-sched-input-bg': '#FFFFFF',
        '--boomi-sched-input-fg': '#111827',
        '--boomi-sched-input-border': '#E5E7EB',
        '--boomi-sched-input-shadow': '0 1px 2px rgba(17,24,39,0.04)',
        '--boomi-sched-input-border-focus': 'var(--plex-blue)',
        '--boomi-sched-input-shadow-focus': '0 0 0 4px rgba(0,150,213,0.15)',
        '--boomi-sched-checkbox-border': '#D1D5DB',
        '--boomi-sched-checkbox-bg': '#FFFFFF',
        '--boomi-sched-checkbox-bg-checked': 'var(--plex-blue)',
        '--boomi-sched-checkbox-symbol': '#FFFFFF',
        '--boomi-sched-action-bg': '#FFFFFF',
        '--boomi-sched-action-fg': 'var(--plex-blue)',
        '--boomi-sched-action-border': '#E5E7EB',
        '--boomi-sched-action-shadow': '0 1px 2px rgba(17,24,39,0.06)',
        '--boomi-sched-action-bg-hover': '#F3F4F6',
  
        /* Connector */
        '--boomi-conn-bg': '#FFFFFF',
        '--boomi-conn-border': '#E5E7EB',
        '--boomi-conn-card-shadow': '0 1px 3px rgba(17,24,39,0.08)',
        '--boomi-conn-heading-fg': '#111827',
        '--boomi-conn-field-bg': '#FFFFFF',
        '--boomi-conn-field-border': '#E5E7EB',
        '--boomi-conn-field-label-fg': '#374151',
        '--boomi-conn-field-error-fg': '#B91C1C',
        '--boomi-conn-btn-save-bg': '#10B981',
        '--boomi-conn-btn-save-fg': '#FFFFFF',
        '--boomi-conn-btn-auth-bg': 'var(--plex-blue)',
        '--boomi-conn-btn-auth-fg': '#FFFFFF',
        '--boomi-conn-btn-disabled-bg': '#F3F4F6',
        '--boomi-conn-btn-disabled-fg': '#9CA3AF',
  
        /* SweetAlert */
        '--boomi-swal-bg': '#FFFFFF',
        '--boomi-swal-fg': '#111827',
        '--boomi-swal-border': '1px solid #E5E7EB',
        '--boomi-swal-shadow': '0 16px 48px rgba(17,24,39,0.16)',
        '--boomi-swal-title-fg': '#111827',
        '--boomi-swal-desc-fg': '#4B5563',
        '--boomi-swal-icon-success': '#10B981',
        '--boomi-swal-icon-warning': '#F59E0B',
        '--boomi-swal-icon-error': '#EF4444',
        '--boomi-swal-overlay-bg': 'rgba(17,24,39,0.45)',
      },
  
      /* ========= ROCKWELL AUTOMATION (minimal) ========= */
      rockwell: {
        /* Font */
        '--boomi-font': 'Inter, ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, "Noto Sans", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
        '--default-font-family': 'var(--boomi-font)',
  
        /* Brand tokens */
        '--ra-red': '#CD163F',
        '--ra-orange': '#F58025',
        '--ra-black': '#111111',
  
        /* Root / Page */
        '--boomi-root-bg-color': '#FFFFFF',
        '--boomi-root-fg-color': '#111827',
        '--boomi-page-bg-color': '#FFFFFF',
        '--boomi-page-fg-color': '#111827',
  
        /* Header */
        '--boomi-header-bg-color': '#FFFFFF',
        '--boomi-header-fg-color': '#111827',
        '--boomi-header-fg-hover': 'var(--ra-red)',
        '--boomi-header-border-color': '#E5E7EB',
        '--boomi-header-shadow': '0 1px 2px rgba(17,24,39,0.06)',
  
        /* Buttons */
        '--boomi-btn-primary-bg': 'var(--ra-red)',
        '--boomi-btn-primary-fg': '#FFFFFF',
        '--boomi-btn-primary-border': 'transparent',
        '--boomi-btn-primary-shadow': '0 1px 2px rgba(205,22,63,0.25)',
        '--boomi-btn-primary-bg-hover': '#B91236',
        '--boomi-btn-primary-bg-active': '#A40F31',
  
        '--boomi-btn-secondary-bg': '#F3F4F6',
        '--boomi-btn-secondary-fg': '#111827',
        '--boomi-btn-secondary-border': '#E5E7EB',
        '--boomi-btn-secondary-shadow': '0 1px 2px rgba(17,24,39,0.06)',
        '--boomi-btn-secondary-bg-hover': '#E5E7EB',
        '--boomi-btn-secondary-bg-active': '#D1D5DB',
  
        /* Inputs */
        '--boomi-input-bg': '#FFFFFF',
        '--boomi-input-fg': '#111827',
        '--boomi-input-placeholder': '#6B7280',
        '--boomi-input-border': '#E5E7EB',
        '--boomi-input-shadow': '0 1px 2px rgba(17,24,39,0.04)',
        '--boomi-input-border-focus': 'var(--ra-red)',
        '--boomi-input-shadow-focus': '0 0 0 4px rgba(205,22,63,0.15)',
        '--boomi-input-outline-focus': 'transparent',
  
        /* Tables */
        '--boomi-table-header-bg': '#F9FAFB',
        '--boomi-table-header-fg': '#374151',
        '--boomi-table-header-border': '#E5E7EB',
        '--boomi-table-row-odd-bg': '#FFFFFF',
        '--boomi-table-row-even-bg': '#FAFAFA',
        '--boomi-table-row-hover-shadow': 'inset 0 0 0 9999px rgba(245,128,37,0.06)',
  
        /* Cards */
        '--boomi-card-border': '#E5E7EB',
        '--boomi-card-bg': '#FFFFFF',
        '--boomi-card-shadow': '0 1px 3px rgba(17,24,39,0.08)',
        '--boomi-card-hover-shadow': '0 2px 6px rgba(17,24,39,0.12)',
        '--boomi-card-hover-scale': 'none',
  
        /* Menus */
        '--boomi-menu-bg': '#FFFFFF',
        '--boomi-menu-fg': '#111827',
        '--boomi-menu-border': '#E5E7EB',
        '--boomi-menu-shadow': '0 8px 24px rgba(17,24,39,0.08)',
        '--boomi-menu-item-bg': 'transparent',
        '--boomi-menu-item-bg-hover': 'rgba(245,128,37,0.08)',
        '--boomi-menu-item-fg': '#111827',
        '--boomi-menu-item-fg-hover': '#111827',
        '--boomi-menu-divider': '#E5E7EB',
        '--boomi-menu-danger-fg': '#B91C1C',
        '--boomi-menu-danger-fg-hover': '#991B1B',
        '--boomi-menu-danger-bg-hover': '#FEE2E2',
  
        /* Modal */
        '--boomi-modal-overlay-bg': 'rgba(17,24,39,0.45)',
        '--boomi-modal-bg': '#FFFFFF',
        '--boomi-modal-fg': '#111827',
        '--boomi-modal-border': '1px solid #E5E7EB',
        '--boomi-modal-shadow': '0 16px 48px rgba(17,24,39,0.16)',
        '--boomi-modal-close-fg': '#6B7280',
        '--boomi-modal-close-hover-fg': '#111827',
  
        /* Input (stateful) */
        '--boomi-input-bg-disabled': '#F9FAFB',
        '--boomi-input-fg-disabled': '#9CA3AF',
        '--boomi-input-border-disabled': '#E5E7EB',
        '--boomi-input-border-invalid': '#F87171',
        '--boomi-input-outline-invalid': 'rgba(248,113,113,0.25)',
  
        /* Form text */
        '--boomi-form-label-fg': '#374151',
        '--boomi-form-helper-fg': '#6B7280',
        '--boomi-form-error-fg': '#B91C1C',
        '--boomi-form-required-fg': '#DC2626',
  
        /* Select */
        '--boomi-select-bg': '#FFFFFF',
        '--boomi-select-fg': '#111827',
        '--boomi-select-border': '#E5E7EB',
        '--boomi-select-shadow': '0 1px 2px rgba(17,24,39,0.04)',
        '--boomi-select-border-focus': 'var(--ra-red)',
        '--boomi-select-shadow-focus': '0 0 0 4px rgba(205,22,63,0.15)',
        '--boomi-select-icon': '#6B7280',
        '--boomi-options-bg': '#FFFFFF',
        '--boomi-options-fg': '#111827',
        '--boomi-options-border': '#E5E7EB',
        '--boomi-options-shadow': '0 8px 24px rgba(17,24,39,0.10)',
        '--boomi-options-search-bg': '#F9FAFB',
        '--boomi-option-bg-active': 'rgba(245,128,37,0.10)',
        '--boomi-option-fg-selected': '#111827',
  
        /* Ajax Loader */
        '--boomi-loader-dot-bg': 'var(--ra-red)',
        '--boomi-loader-dot-size': '0.75rem',
        '--boomi-loader-msg-fg': '#4B5563',
        '--boomi-loader-dot1-opacity': '1',
        '--boomi-loader-dot2-opacity': '1',
        '--boomi-loader-dot3-opacity': '1',
  
        /* Spinner */
        '--boomi-spinner-overlay-bg': 'rgba(255,255,255,0.65)',
        '--boomi-spinner-ring-color': 'var(--ra-red)',
        '--boomi-spinner-ping-color': 'var(--ra-orange)',
        '--boomi-spinner-message-fg': '#374151',
        '--boomi-spinner-size': '3.25rem',
        '--boomi-spinner-border-width': '4px',
  
        /* Wizard */
        '--boomi-wizard-step-dot-bg': '#F3F4F6',
        '--boomi-wizard-step-dot-fg': '#374151',
        '--boomi-wizard-step-dot-border': '#E5E7EB',
        '--boomi-wizard-step-dot-shadow': '0 1px 2px rgba(17,24,39,0.04)',
        '--boomi-wizard-step-dot-bg-active': 'var(--ra-red)',
        '--boomi-wizard-step-dot-fg-active': '#FFFFFF',
        '--boomi-wizard-step-dot-border-active': 'transparent',
        '--boomi-wizard-step-dot-shadow-active': '0 1px 2px rgba(205,22,63,0.25)',
        '--boomi-wizard-step-dot-bg-completed': '#10B981',
        '--boomi-wizard-step-dot-fg-completed': '#064E3B',
        '--boomi-wizard-step-dot-border-completed': 'transparent',
        '--boomi-wizard-step-dot-shadow-completed': '0 1px 2px rgba(16,185,129,0.25)',
        '--boomi-wizard-connector-bg': '#E5E7EB',
        '--boomi-wizard-label-fg': '#4B5563',
        '--boomi-wizard-card-bg': '#FFFFFF',
        '--boomi-wizard-card-fg': '#111827',
        '--boomi-wizard-card-border': '#E5E7EB',
        '--boomi-wizard-card-shadow': '0 1px 3px rgba(17,24,39,0.08)',
        '--boomi-wizard-link-fg': 'var(--ra-red)',
        '--boomi-wizard-link-fg-hover': '#A40F31',
        '--boomi-wizard-link-strong-fg': '#111827',
  
        /* Notifications */
        '--boomi-notice-warning-bg': '#FFFBEB',
        '--boomi-notice-warning-fg': '#92400E',
        '--boomi-notice-warning-border': '#FDE68A',
        '--boomi-notice-success-bg': '#ECFDF5',
        '--boomi-notice-success-fg': '#065F46',
        '--boomi-notice-success-border': '#A7F3D0',
        '--boomi-notice-error-bg': '#FEF2F2',
        '--boomi-notice-error-fg': '#991B1B',
        '--boomi-notice-error-border': '#FECACA',
        '--boomi-notice-shadow': '0 1px 2px rgba(17,24,39,0.06)',
        '--boomi-notice-radius': '.5rem',
  
        /* Update panel */
        '--boomi-update-bg': '#FFFFFF',
        '--boomi-update-fg': '#111827',
        '--boomi-update-border': '#E5E7EB',
        '--boomi-update-shadow': '0 2px 6px rgba(17,24,39,0.10)',
        '--boomi-update-title-fg': '#111827',
        '--boomi-update-desc-fg': '#4B5563',
        '--boomi-update-radius': '.5rem',
        '--boomi-update-content': '#111827',
  
        /* Tabs */
        '--boomi-tablist-border': '#E5E7EB',
        '--boomi-tab-bg': '#FFFFFF',
        '--boomi-tab-fg': '#374151',
        '--boomi-tab-border': '#E5E7EB',
        '--boomi-tab-bg-hover': '#F3F4F6',
        '--boomi-tab-bg-active': 'rgba(205,22,63,0.08)',
        '--boomi-tab-fg-active': '#111827',
        '--boomi-tab-border-active': 'var(--ra-red)',
  
        /* Maps */
        '--boomi-accent': 'var(--ra-red)',
        '--boomi-muted': '#6B7280',
        '--boomi-map-line': '#CBD5E1',
        '--boomi-map-line-width': '2px',
        '--boomi-map-line-filter': 'none',
        '--boomi-map-heading-fg': '#111827',
        '--boomi-map-card-bg': '#FFFFFF',
        '--boomi-map-card-border': '#E5E7EB',
        '--boomi-map-card-shadow': '0 1px 3px rgba(17,24,39,0.08)',
        '--boomi-map-card-shadow-hover': '0 2px 6px rgba(17,24,39,0.12)',
        '--boomi-map-card-transform-hover': 'none',
        '--boomi-map-source-bg-mapped': '#F1F5F9',
        '--boomi-map-source-border-mapped': '#E5E7EB',
        '--boomi-map-source-outline': '#E5E7EB',
        '--boomi-map-target-bg-mapped': '#F0FDF4',
        '--boomi-map-target-border-mapped': '#DCFCE7',
        '--boomi-map-target-outline': '#DCFCE7',
        '--boomi-map-func-bg': '#F9FAFB',
        '--boomi-map-func-fg': '#111827',
        '--boomi-map-func-title-fg': '#111827',
        '--boomi-map-pin-source-bg': 'var(--ra-orange)',
        '--boomi-map-pin-target-bg': '#10B981',
        '--boomi-map-pin-input-bg': '#F59E0B',
        '--boomi-map-pin-output-bg': '#6366F1',
        '--boomi-map-pin-badge-bg': '#EF4444',
        '--boomi-map-pin-badge-fg': '#FFFFFF',
        '--boomi-map-pin-danger-bg': '#EF4444',
        '--boomi-map-pulse-color': 'rgba(205,22,63,0.20)',
        '--boomi-map-pin-pulse': 'boomi-map-pulse 1.1s ease-in-out infinite',
        '--boomi-map-add-bg': '#F3F4F6',
        '--boomi-map-add-fg': '#111827',
        '--boomi-map-add-border': '#E5E7EB',
        '--boomi-map-add-shadow': '0 1px 2px rgba(17,24,39,0.06)',
        '--boomi-map-add-bg-hover': '#E5E7EB',
  
        /* Schedule */
        '--boomi-sched-card-bg': '#FFFFFF',
        '--boomi-sched-card-fg': '#111827',
        '--boomi-sched-card-border': '#E5E7EB',
        '--boomi-sched-card-shadow': '0 1px 3px rgba(17,24,39,0.08)',
        '--boomi-sched-card-shadow-hover': '0 2px 6px rgba(17,24,39,0.12)',
        '--boomi-sched-card-radius': '.5rem',
        '--boomi-sched-header-bg': '#F9FAFB',
        '--boomi-sched-header-fg': '#111827',
        '--boomi-sched-header-border': '#E5E7EB',
        '--boomi-sched-header-shadow': '0 1px 2px rgba(17,24,39,0.06)',
        '--boomi-sched-toggle-fg': '#6B7280',
        '--boomi-sched-toggle-fg-hover': '#111827',
        '--boomi-sched-row-bg': '#FFFFFF',
        '--boomi-sched-row-border': '#E5E7EB',
        '--boomi-sched-row-shadow': '0 1px 2px rgba(17,24,39,0.04)',
        '--boomi-sched-row-hover-shadow': 'inset 0 0 0 9999px rgba(205,22,63,0.06)',
        '--boomi-sched-label-fg': '#374151',
        '--boomi-sched-helper-fg': '#6B7280',
        '--boomi-sched-error-fg': '#B91C1C',
        '--boomi-sched-select-bg': '#FFFFFF',
        '--boomi-sched-select-fg': '#111827',
        '--boomi-sched-select-border': '#E5E7EB',
        '--boomi-sched-select-shadow': '0 1px 2px rgba(17,24,39,0.04)',
        '--boomi-sched-select-border-focus': 'var(--ra-red)',
        '--boomi-sched-select-shadow-focus': '0 0 0 4px rgba(205,22,63,0.15)',
        '--boomi-sched-input-bg': '#FFFFFF',
        '--boomi-sched-input-fg': '#111827',
        '--boomi-sched-input-border': '#E5E7EB',
        '--boomi-sched-input-shadow': '0 1px 2px rgba(17,24,39,0.04)',
        '--boomi-sched-input-border-focus': 'var(--ra-red)',
        '--boomi-sched-input-shadow-focus': '0 0 0 4px rgba(205,22,63,0.15)',
        '--boomi-sched-checkbox-border': '#D1D5DB',
        '--boomi-sched-checkbox-bg': '#FFFFFF',
        '--boomi-sched-checkbox-bg-checked': 'var(--ra-red)',
        '--boomi-sched-checkbox-symbol': '#FFFFFF',
        '--boomi-sched-action-bg': '#FFFFFF',
        '--boomi-sched-action-fg': 'var(--ra-red)',
        '--boomi-sched-action-border': '#E5E7EB',
        '--boomi-sched-action-shadow': '0 1px 2px rgba(17,24,39,0.06)',
        '--boomi-sched-action-bg-hover': '#F3F4F6',
  
        /* Connector */
        '--boomi-conn-bg': '#FFFFFF',
        '--boomi-conn-border': '#E5E7EB',
        '--boomi-conn-card-shadow': '0 1px 3px rgba(17,24,39,0.08)',
        '--boomi-conn-heading-fg': '#111827',
        '--boomi-conn-field-bg': '#FFFFFF',
        '--boomi-conn-field-border': '#E5E7EB',
        '--boomi-conn-field-label-fg': '#374151',
        '--boomi-conn-field-error-fg': '#B91C1C',
        '--boomi-conn-btn-save-bg': '#10B981',
        '--boomi-conn-btn-save-fg': '#FFFFFF',
        '--boomi-conn-btn-auth-bg': 'var(--ra-red)',
        '--boomi-conn-btn-auth-fg': '#FFFFFF',
        '--boomi-conn-btn-disabled-bg': '#F3F4F6',
        '--boomi-conn-btn-disabled-fg': '#9CA3AF',
  
        /* SweetAlert */
        '--boomi-swal-bg': '#FFFFFF',
        '--boomi-swal-fg': '#111827',
        '--boomi-swal-border': '1px solid #E5E7EB',
        '--boomi-swal-shadow': '0 16px 48px rgba(17,24,39,0.16)',
        '--boomi-swal-title-fg': '#111827',
        '--boomi-swal-desc-fg': '#4B5563',
        '--boomi-swal-icon-success': '#10B981',
        '--boomi-swal-icon-warning': '#F59E0B',
        '--boomi-swal-icon-error': 'var(--ra-red)',
        '--boomi-swal-overlay-bg': 'rgba(17,24,39,0.45)',
      },
    },
  };
  