/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { customFields } from './customFields';
export type TradacomsConnectorRecord = {
    /**
     * The ID of the account in which you ran this record.
     */
    account: string;
    /**
     * The type of action with which this record corresponds — Send for an outbound interchange, Get for an inbound interchange using the Disk, FTP, or SFTP communication method, or Listen for an inbound interchange using the AS2 or HTTP communication method.
     */
    actionType: string;
    /**
     * The code that enables the receiving trading partner to identify whether the message contains data for a particular type of application.
     */
    applicationReference?: string;
    /**
     * The Runtime ID from which you process this record.
     */
    atomId: string;
    /**
     * The value is Trading Partner for a Tradacoms trading partner Send operation, or Start for a Tradacoms trading partner Listen operation.
     */
    connectorName: string;
    /**
     * Tradacoms is the connector type for any record.
     */
    connectorType: string;
    /**
     * Custom fields based on the configured fields on the **Document Tracking** tab of the **Setup** page. The names of the fields are dependent upon your account setup.
     */
    customFields: customFields;
    /**
     * The date of the message delivery.
     */
    date?: string;
    /**
     * The processing date and time of this record. The format is *yyyy-MM-dd'T'HH:mm:ss'Z'*, such as 2022-08-10T15:32:00Z.
     */
    dateProcessed: string;
    /**
     * The numerical index of this record in the run.
     */
    documentIndex?: number;
    /**
     * Any error message associated with this record. Omit this field for a successful interchange.
     */
    errorMessage: string;
    /**
     * The ID of the run.
     */
    executionId: string;
    /**
     * The number generated by the sending trading partner to uniquely reference the transmitted file.
     */
    fileGenerationNumber?: string;
    /**
     * The number generated to uniquely reference a copy of the transmitted file.
     */
    fileVersionNumber?: string;
    /**
     * The ID of this record.
     */
    id: string;
    /**
     * The code identifying the type of message.
     */
    messageType?: string;
    /**
     * The name of the operation component from which you processed the record.
     */
    operationName: string;
    /**
     * The name of the receiving trading partner.
     */
    receiverName?: string;
    /**
     * The receiving trading partner’s reference for the message, if known to the sending trading partner.
     */
    receiverTransmissionReference?: string;
    /**
     * The name of the sending trading partner.
     */
    senderName?: string;
    /**
     * The sending trading partner’s reference for the message.
     */
    senderTransmissionReference?: string;
    /**
     * The size, in bytes, of the document that corresponds to this record.
     */
    size?: number;
    /**
     * Whether the record is a success or error.
     */
    successful?: boolean;
    /**
     * The time of the message delivery.
     */
    time?: string;
    /**
     * The code for the message transmission priority.
     */
    transmissionPriorityCode?: string;
    /**
     * The validation report, which contains descriptions of segment validation errors.
     */
    validationReport?: string;
    /**
     * The validation status — either Success or Errors.
     */
    validationStatus?: string;
};

