/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type UNHControlInfo = {
    assocAssignedCode?: string;
    commonAccessRef?: string;
    controllingAgency?: UNHControlInfo.controllingAgency;
    release?: UNHControlInfo.release;
    version?: UNHControlInfo.version;
};
export namespace UNHControlInfo {
    export enum controllingAgency {
        AA = 'AA',
        AB = 'AB',
        AC = 'AC',
        AD = 'AD',
        AE = 'AE',
        CC = 'CC',
        CE = 'CE',
        EC = 'EC',
        ED = 'ED',
        EE = 'EE',
        EN = 'EN',
        ER = 'ER',
        EU = 'EU',
        EX = 'EX',
        IA = 'IA',
        KE = 'KE',
        LI = 'LI',
        OD = 'OD',
        RI = 'RI',
        RT = 'RT',
        UN = 'UN',
    }
    export enum release {
        EDIFACTRELEASE_1 = 'EDIFACTRELEASE_1',
        EDIFACTRELEASE_2 = 'EDIFACTRELEASE_2',
        EDIFACTRELEASE_902 = 'EDIFACTRELEASE_902',
        EDIFACTRELEASE_911 = 'EDIFACTRELEASE_911',
        EDIFACTRELEASE_912 = 'EDIFACTRELEASE_912',
        EDIFACTRELEASE_921 = 'EDIFACTRELEASE_921',
        EDIFACTRELEASE_932 = 'EDIFACTRELEASE_932',
        EDIFACTRELEASE_93A = 'EDIFACTRELEASE_93A',
        EDIFACTRELEASE_94A = 'EDIFACTRELEASE_94A',
        EDIFACTRELEASE_94B = 'EDIFACTRELEASE_94B',
        EDIFACTRELEASE_95A = 'EDIFACTRELEASE_95A',
        EDIFACTRELEASE_95B = 'EDIFACTRELEASE_95B',
        EDIFACTRELEASE_96A = 'EDIFACTRELEASE_96A',
        EDIFACTRELEASE_96B = 'EDIFACTRELEASE_96B',
        EDIFACTRELEASE_97A = 'EDIFACTRELEASE_97A',
        EDIFACTRELEASE_97B = 'EDIFACTRELEASE_97B',
        EDIFACTRELEASE_98A = 'EDIFACTRELEASE_98A',
        EDIFACTRELEASE_98B = 'EDIFACTRELEASE_98B',
        EDIFACTRELEASE_99A = 'EDIFACTRELEASE_99A',
        EDIFACTRELEASE_99B = 'EDIFACTRELEASE_99B',
        EDIFACTRELEASE_00A = 'EDIFACTRELEASE_00A',
        EDIFACTRELEASE_00B = 'EDIFACTRELEASE_00B',
        EDIFACTRELEASE_01A = 'EDIFACTRELEASE_01A',
        EDIFACTRELEASE_01B = 'EDIFACTRELEASE_01B',
        EDIFACTRELEASE_02A = 'EDIFACTRELEASE_02A',
        EDIFACTRELEASE_02B = 'EDIFACTRELEASE_02B',
        EDIFACTRELEASE_03A = 'EDIFACTRELEASE_03A',
        EDIFACTRELEASE_03B = 'EDIFACTRELEASE_03B',
        EDIFACTRELEASE_04A = 'EDIFACTRELEASE_04A',
        EDIFACTRELEASE_04B = 'EDIFACTRELEASE_04B',
        EDIFACTRELEASE_05A = 'EDIFACTRELEASE_05A',
        EDIFACTRELEASE_05B = 'EDIFACTRELEASE_05B',
        EDIFACTRELEASE_06A = 'EDIFACTRELEASE_06A',
        EDIFACTRELEASE_06B = 'EDIFACTRELEASE_06B',
        EDIFACTRELEASE_07A = 'EDIFACTRELEASE_07A',
        EDIFACTRELEASE_07B = 'EDIFACTRELEASE_07B',
        EDIFACTRELEASE_08A = 'EDIFACTRELEASE_08A',
        EDIFACTRELEASE_08B = 'EDIFACTRELEASE_08B',
        EDIFACTRELEASE_09A = 'EDIFACTRELEASE_09A',
        EDIFACTRELEASE_09B = 'EDIFACTRELEASE_09B',
    }
    export enum version {
        EDIFACTVERSION_1 = 'EDIFACTVERSION_1',
        EDIFACTVERSION_2 = 'EDIFACTVERSION_2',
        EDIFACTVERSION_4 = 'EDIFACTVERSION_4',
        EDIFACTVERSION_88 = 'EDIFACTVERSION_88',
        EDIFACTVERSION_89 = 'EDIFACTVERSION_89',
        EDIFACTVERSION_90 = 'EDIFACTVERSION_90',
        EDIFACTVERSION_D = 'EDIFACTVERSION_D',
        EDIFACTVERSION_S = 'EDIFACTVERSION_S',
    }
}

